site_name: Lilia Documentation
site_description: Official documentation for the Lilia Framework
site_author: Lilia Framework Team
site_url: 'https://liliaframework.github.io/'
repo_url: 'https://github.com/LiliaFramework/Lilia'
repo_name: LiliaFramework/Lilia
edit_uri: 'edit/main/docs/docs/'
plugins:
  - search
  - awesome-pages
theme:
  name: material
  logo: assets/logo_small.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.copy
    - navigation.tracking
    - navigation.footer
  font:
    text: Noto Sans
    code: Roboto Mono
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: teal
      accent: lavender
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: teal
      accent: lavender
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences